### ISSUE TITLE
Neue Seite online

### ISSUE THREAD

**Issue by FlorianRappl** [DotNetRegensburg/dotnetregensburg.github.io#1]
Hi zusammen,

ich hab mir mal kurz Zeit genommen und ein Design zusammengeschustert. Die Seite ist natürlich schon online (http://dotnetregensburg.github.io). Bis jetzt sind nur die letzten 3 und der aktuelle Vortrag drin.

Ich hab ein kleines Skript geschrieben, dass auch die anderen (automatisiert) erstellen könnte. Ein wenig Handarbeit ist jedoch zusätzlich noch notwendig, z.B. würde ich gerne aussagekräftige Bilder zum Vortrag erstellen. 

Meinung zum Design? Verbesserungen etc.? Was fehlt?

Ich schreibe jetzt Tom mal an...

**Comment by RolandKoenig** [comment]
Cool, sieht gut aus.
Respekt :-)

**Comment by FlorianRappl** [comment]
Ich mach das Issue mal wieder auf - vermute, dass es nur aus Versehen geschlossen wurde.

**Comment by RolandKoenig** [comment]
Jop, falschen Button erwischt. Sorry 
Wer kommt auch schon drauf, auf den auffällig grünen Button zu drücken ;)

**Comment by danielmurrmann** [comment]
Schließe mich hier voll und ganz an. Die Seite ist für die erste Version wirklich sehr gut geworden. Vorschlag zur Verbesserung: Im Header sollte immer etwas von der UG Regensburg stehen. Das wechselt aktuell je nachdem wie man auf der Seite navigiert!

**Comment by FlorianRappl** [comment]
Hm meinst du also, dass in der schwarzen Navigationsleiste der Titel stehen sollte? Obwohl das viele Seiten so machen halte ich das in unserem Fall für Platzverschwendung. Die Leute wissen ja auf welcher Seite sie sind. Außerdem steht das alles nochmal in dem Tab im Browser. Und die URL ist auch ziemlich eindeutig.

Auf manchen Seiten bringt das Logo / der Titel einen Mehrwert bzgl. der Navigation; aber wir haben nur diese eine Seite mit dem Design.
