### ISSUE TITLE
Montag, 25.07.2016: IoT - Herausforderungen und Chancen

### ISSUE THREAD

**Issue by FlorianRappl** [DotNetRegensburg/dotnetregensburg.github.io#11]
Wollte auch hier auf den nächsten Vortrag hinweisen.

**IoT - Herausforderungen und Chancen**

_Für viele Unternehmen bietet IoT zusätzliche Möglichkeiten um neue Geschäftsmodelle zu realisieren. Neben dem großen wirtschaftlichen Potential ergeben sich aber auch technische Aufgabenstellungen, die mitunter sehr komplex sind und sich nicht einfach und generisch lösen lassen. Daraus entstehen Räume für innovative Ideen, um die Vielfalt der neuartigen Use Cases technisch abzubilden._

_Der Vortag behandelt Herausforderungen im Zusammenhang mit Digitaler Transformation wie zum Beispiel Security, Gerätekommunikation, aber auch IoT Business Models. Für ausgewählte Aufgabenstellungen werden Lösungsansätze diskutiert und Möglichkeiten der Umsetzung anhand einer generischen Plattform und Prototypen demonstriert. Dabei werden neben unterschiedlichen Microsoft-Technologien auch Testimplementierungen basierend auf Raspberry PI und Netduino verwendet._

Wird sicher wieder interessant! Beginn ist 18:30 Uhr.

Bitte in den Doodle eintragen: http://doodle.com/poll/qy92qqdf9d7e48zz

**Comment by FlorianRappl** [comment]
@feO2x kannst du heute wieder Equipment für die Aufnahme mitnehmen? Wenn nicht, tue ich das (und installiere endlich mal wieder Camtasia auf meinem Laptop!).

Bis später!

**Comment by feO2x** [comment]
Ich kann Webcam und Surface Pro mitnehmen - hast du zufälligerweise noch ein Stativ?

**Comment by FlorianRappl** [comment]
Leider nicht!

**Comment by feO2x** [comment]
Dann frage ich nochmal einen Kollegen von mir.
