### ISSUE TITLE
Folien-Downloads

### ISSUE THREAD

**Issue by feO2x** [DotNetRegensburg/dotnetregensburg.github.io#14]
Kurze Frage: ich habe heute die Folien von Christian Weyer zu seinem Vortrag am Dienstag bekommen, damit wir sie auf der Website bereitstellen können.

Soll ich diese direkt mit in dieses Repo einchecken, und dann die URL darauf verlinken? Oder haben wir irgendwo einen Fileserver?

**Comment by FlorianRappl** [comment]
Wir haben ein Extra Repository für Downloads: https://github.com/DotNetRegensburg/Downloads

Der Weg hier ist einen neuen Orphan Branch zu erstellen (ohne Parent) - Name "2016-10-04" (so zumindest war die Konvention bis hierhin) und dann dort alle Dateien (entpackt) hinzulegen. Das entpacken finde ich daher sinnvoll, da es schon als ein Bundle geliefert wird und man sich dadurch zusätzliche Extracts sparen kann.

Kannst du natürlich alles entscheiden / machen wie du willst.

@feO2x Vielen Dank für die Orga - ich hoffe im November mal wieder dabei sein zu können!

**Comment by feO2x** [comment]
Alles klar, ich hab's so hochgeladen.
