### ISSUE TITLE
Vortrag für November?

### ISSUE THREAD

**Issue by FlorianRappl** [DotNetRegensburg/dotnetregensburg.github.io#15]
Haben wir für November bereits einen Vortrag? Bzw. wie sieht es mit der Pipeline aus?

Ansonsten kann ich helfen die Pipeline zu füllen bzw. spontan einen für November anzubieten.

**Comment by feO2x** [comment]
Roland spricht im November zu Xamarin, ich wahrscheinlich im Dezember, für Januar bin ich gerade mit Dominick Baier am verhandeln. Wenn du möchtest, kannst du aber auch gerne im Dezember sprechen.

**Comment by FlorianRappl** [comment]
Ne - passt alles super! Ich hab immer ein Thema am Start, würde aber nur einen Vortrag halten wenn sonst nichts in der Pipe ist. Wenn der November Termin in die ersten 2 Wochen fällt schaffe ich es sogar mal wieder zu einem Meeting!

Danke @feO2x  und bis bald hoffentlich!

**Comment by RolandKoenig** [comment]
Im Moment hätte ich eher Ende November angepeilt.
Aber ich schau mal, vielleicht komm ich früher dazu. 

Viele Grüße
