### ISSUE TITLE
YouTube Channel

### ISSUE THREAD

**Issue by feO2x** [DotNetRegensburg/dotnetregensburg.github.io#16]
Ich würde gerne einen YouTube Channel für unsere User Group einrichten und habe dazu folgende Fragen:
* Haben wir über die Adresse info@dotnet-regensburg.de bereits ein Google-Konto aktiviert?
* Falls nein, kann mir jemand Zugriff auf diese Adresse geben? Muss ich dazu mit Thomas reden?

**Comment by FlorianRappl** [comment]
Super Idee 👍 !

Gibt kein Google Konto soweit ich weiß. Ja, ich glaube Thomas wäre der richtige Ansprechpartner.

**Comment by feO2x** [comment]
YouTube Channel ist online, das erste Video ist auch bereits hochgeladen:
https://www.youtube.com/channel/UC71NFJ4PoJB2mh4I5l5oaGA

**Comment by FlorianRappl** [comment]
Sehr cool! Ich versuche später meine existierenden Videos zu transferieren. 

@feO2x Das Logo / Intro gefällt mir sehr gut 👍
