### ISSUE TITLE
Markdown Links werden nicht geparst, wenn sie Teil der YAML Definition sind

### ISSUE THREAD

**Issue by feO2x** [DotNetRegensburg/dotnetregensburg.github.io#17]
Wenn man im YAML-Teil einer Talk-Beschreibung einen Markdown Link einfügt, dann wird dieser im resultierenden HTML Dokument nicht als HTML Anchor dargestellt (siehe Bild).

![image](https://cloud.githubusercontent.com/assets/7884158/20267743/6982b9f0-aa7c-11e6-8f34-375462b9ce4c.png)

@FlorianRappl, sollten wir dieses Problem einfach umgehen, indem wir <a> Tags verwenden, oder kann man das relativ einfach fixen? Ehrlich gesagt bin ich nicht ganz so firm mit Jekyll Bootstrap, um das aus dem Stehgreif beantworten zu können.

**Comment by FlorianRappl** [comment]
Wir können einfach Tags verwenden. Wichtig sind nur die Quotes; daher lief der Build anfangs nicht (YAML is relativ lasch mit Strings, allerdings wird es zu einem Problem sobald ein weiterer Doppelpunkt auftaucht).

**Comment by FlorianRappl** [comment]
Ich hab das Problem durch einen entsprechenden Filter gelöst. Wir können nun auch Markdown in der Description verwenden!

**Comment by feO2x** [comment]
Super, vielen Dank!
