### ISSUE TITLE
Kommende Vorträge?

### ISSUE THREAD

**Issue by FlorianRappl** [DotNetRegensburg/dotnetregensburg.github.io#18]
Hallo zusammen,

nachdem ich noch keinen (und vermutlich wird es auch keinen geben) Vortrag für Dezember gesehen habe frage ich mich wie es mit anstehenden Vorträgen aussieht?

Welche Monate sind frei bzw. ab welchen Monat haben wir nichts mehr?

Viele Grüße, eine frohe Weihnachtszeit und einen guten Rutsch!

**Comment by feO2x** [comment]
Aktuell haben wir noch ein rechtliches Problem mit der Techbase, sodass wir keinen Raum reservieren können. Genau deswegen wird der Dezembertermin, wo ich vorgetragen hätte, nicht stattfinden und stattdessen in den Januar verschoben. Eine Meldung dazu werde ich Anfang nächster Woche rausgeben.

Ansonsten bin ich noch im Gespräch mit Dominick Baier, der den Identity Server 4 bei uns in einem Talk vorstellen könnte. Und @FlorianRappl, hattest du nicht auch einen Talk? Damit wären wir schon mal bis ca. März abgedeckt.

**Comment by FlorianRappl** [comment]
Ja würde ich gerne machen. Auf die Meldung bin ich dann schon gespannt!

Vielen Dank fürs Update, schöne Weihnachtsfeiertage und einen guten Rutsch wünsch ich schon mal.
