### ISSUE TITLE
Videolink und Downloads von Januar 2017 Talk werden nicht angezeigt

### ISSUE THREAD

**Issue by feO2x** [DotNetRegensburg/dotnetregensburg.github.io#19]
Hey @FlorianRappl,

wir haben folgendes Problem: beim Januar 2017 Talk habe ich einen Link zum GitHub Repo mit Slides und Beispielcode sowie einen Link zum Video hinzugefügt, leider werden diese aber nicht in die Website hinzugefügt. Alle anderen Inhalte sind aber da, weswegen ich vermute, das er bei der Projektion an einem bestimmten Punkt abbricht? Ich bin aber der Meinung, dass das YAML am Anfang richtig formatiert ist.

Kannst du da bei Gelegenheit mal einen Blick drauf werfen?

**Comment by FlorianRappl** [comment]
Mach ich morgen. Sollte das Problem Samstag noch da sein, dann bitte einfach nochmal erinnern. Danke @feO2x!

**Comment by FlorianRappl** [comment]
Erledigt. Video war unter Speaker, statt direkt im Root (selbes galt für die Downloads).

**Comment by feO2x** [comment]
Sorry, manchmal fehlt mir echt der Durchblick - herzlichen Dank @FlorianRappl

**Comment by FlorianRappl** [comment]
No problemo! War alles gut :)
