### ISSUE TITLE
Sprecher für September

### ISSUE THREAD

**Issue by FlorianRappl** [DotNetRegensburg/dotnetregensburg.github.io#2]
Der für September geplante Vortrag findet nun im Oktober statt. Daher ist für den 28.09. noch kein Sprecher eingeplant. Wer einen möglichen Sprecher kennt oder selbst einen Vortrag halten möchte, kann mich dazu gerne anschreiben.

Sollte sich kein Sprecher finden wird der **28.09.** für Diskussionen rund um die .NET UG Regensburg genutzt. Hier wird u.a. über die neue Homepage diskutiert.

**Comment by FlorianRappl** [comment]
So kurzfristig konnten wir keinen externen Sprecher mehr finden. Anstelle dessen wird nun folgendes Programm angeboten:

#### C# 6 in 30 Minuten (+ anschließende Diskussionsrunde)

_Im Visual Studio 2015 wurde die .NET Compiler Platform mit der aktuellsten Version der C# Programmiersprache integriert. Die Änderungen von C# 6 gegenüber seinem Vorgänger sind klein aber fein. In einem 30 Minuten Hands-on werden die neuen Features vorgestellt und deren Einsatz erläutert. Nach dem Vortrag wird in eine Diskussionsrunde übergegangen, welche die zukünftige Ausrichtung und mögliche Veränderungen in der .NET Usergroup Regensburg offen debattiert._

Ich werde diesen Vortrag in (wirklich) 30 Minuten halten. Ich würde danach auch die Diskussionsrunde moderieren, wobei hier vermutlich wenig Moderation erforderlich ist und wir uns einfach nur zusammen setzen und über die Webseite, zukünftige Sprecher, mögliche Events und weitere Themen diskutiert wird.

Könnte jemand (z.B. @feO2x, @fancyDevelopment, @RolandKoenig) die Ankündigung für den Vortrag (+ Diskussionsrunde) in der Facebook Gruppe posten? Vielen Dank!

**Comment by danielmurrmann** [comment]
Hab gerade einen Post in die Facebook Gruppe gestellt!

**Comment by FlorianRappl** [comment]
Perfekt!
