### ISSUE TITLE
Vorträge an der OTH Regensburg?

### ISSUE THREAD

**Issue by feO2x** [DotNetRegensburg/dotnetregensburg.github.io#21]
Hallo zusammen,
Entschuldigung, dass ich für September und Oktober keinen Talk organisieren konnte, dafür hat sich mittlerweile etwas unserer zukünftigen Location getan.
Neben dem Gasthaus Herrmann, das wir prinzipiell nutzen könnten, das aber nicht ganz so gut für Vorträge geeignet ist, habe ich auch noch Kontakt zu einem Student Branch auf dem Campus aufgenommen. Wir könnten unsere Vorträge während der Vorlesungszeit auch an der Fakultät Mathematik / Informatik halten. Vorteil: große Vortragsräume und die Hoffnung, mehr studentische Besucher bei den Vorträgen zu haben.

Was haltet ihr davon, wenn wir teilweise während der Vorlesungszeiten dort unsere Veranstaltungen abhalten würden, mit Unterstützung des lokalen Student Branch?

**Comment by FlorianRappl** [comment]
Einverstanden - klingt sehr gut! Und danke auch für die allgemeine Info.

**Comment by feO2x** [comment]
Wir sind mittlerweile vollständig auf den Campus gewechselt.
