### ISSUE TITLE
Ergebnisse der Diskussionsrunde

### ISSUE THREAD

**Issue by FlorianRappl** [DotNetRegensburg/dotnetregensburg.github.io#3]
Folgendes wurde beim Treffen heute (28.09.2015) beschlossen:
- Wir werden versuchen einen günstigeren Zeitpunkt zu finden. Zunächst wird eine Verschiebung auf 17:30 (und vermutlich Donnerstag) versucht. Langfristig brauchen wir jedoch viel mehr Feedback.
- Der Mailverteiler wird vom IT-Speicher entkoppelt. Es wird künftig auch häufiger Mails (min. 2x vor dem Treffen) geben.
- Für "Workshops" / "Hands-on" bzw. allgemein "Hackathon" oder gar eine Konferenz reicht der Grundstock aus der .NET Usergroup noch nicht aus. Langfristig wären solche Projekte jedoch interessant. Wer dazu beitragen möchte kann sich gerne melden.
- Pizza und Bier gehören eigentlich zu jedem .NET Usergroup Treffen.
- Die Vorträge werden zeitlich auf 2h beschränkt.
- "Show and Tell" könnte entweder als eigenes Event oder im Rahmen der Treffen stattfinden.

Insgesamt wird also versucht die .NET Usergroup wieder näher zum Herz der Community zu bringen. Um zu finden _wo das Herz der Community_ schlägt, brauchen wir allerdings mehr Daten. Jedes Feedback ist daher wertvoll für uns. Eine Umfrage über den idealen Wochentag (Mo, Di, Mi, Do) wird daher möglichst bald auf der Webseite platziert.

**Comment by RolandKoenig** [comment]
Eine Umfrage finde ich eine gute Idee. Hierbei sollten wir auch die ideale Uhrzeit abfragen. In Nürnberg z. B. starten die Vorträge immer erst um 19:00 Uhr und sind eigentlich sehr gut besucht.
Den Punkt "Pizza und Bier" find ich super :+1:

**Comment by FlorianRappl** [comment]
Die Idee war erstmal den geeigneten Tag zu finden und dann (anschließend) die Uhrzeit zu klären. Bin eigentlich auch eher für später; war aber letztes Mal in der Minderheit.

**Comment by feO2x** [comment]
Entschuldigung, dass ich es am Montag nicht geschafft habe, ich hatte leider einiges zu tun.

Ich werde einfach schon mal Feedback geben zu den einzelnen Punkten geben:
- Bier und Pizza klingt gut - nicht-alkoholische Getränke sind damit wohl inbegriffen, nehme ich an (nicht jeder trinkt Bier). Doch wie soll das finanziert werden? Hat die UG so viele Mittel?
- Ich werde mehr Werbung an OTH und Universität für die UG machen - C#/.NET hat sich mittlerweile zu einer echten Alternative für Java entwickelt. Ich denke, dass man einige Studenten und vielleicht auch den einen oder anderen Professor mit abfischen kann. Mit Bier und Pizza können v.a. Studenten gut gelockt werden.
- Donnerstag, 17.30 Uhr halte ich meiner Meinung nach für zu früh. Ich bin wie Flo für 18 bis 19 Uhr - wenn die Vorträge auf zwei Stunden beschränkt werden, hat man danach noch genug vom Abend.
- Vorträge auf zwei Stunden beschränken :+1: Man sollte vielleicht sogar eher eine Stunde Vortrag mit halber Stunde Diskussion anstreben - die meisten Vorträge dauern länger als gedacht. Vielleicht können wir dazu auch ein Informationsblatt für Sprecher zusammenstellen.
- Bei den Wochentagen habe ich keine Präferenzen, allerdings finde ich, dass wir die Treffen möglichst konsistent auf einen Wochentag legen sollten, damit sich bei den Besuchern einbläut "an einem Montag im Monat is .NET UG Tag".

Viele Grüße,
Kenny

**Comment by FlorianRappl** [comment]
Stimme voll und ganz zu :+1:!

Neben :pizza: und :beer: sind natürlich auch andere Getränke :tropical_drink: möglich... Die Verpflegung wird nicht von der Usergroup gestellt, sondern kollektiv bestellt (d.h. wer was möchte muss dafür auch zahlen).
