### ISSUE TITLE
Montag, 23.11.2015: Akka.NET

### ISSUE THREAD

**Issue by FlorianRappl** [DotNetRegensburg/dotnetregensburg.github.io#4]
Wollte auch hier nochmal auf den anstehenden Vortrag hinweisen.

_In der .NET Community wird immer wieder das Konzept des Actor Models angesprochen. Doch was ist das eigentlich? Was kann ich damit machen?_

_Dieser Vortrag beantwortet diese Fragen. Zugleich wird unter Verwendung des Open Source Frameworks akka. net ein Beispiel für ein skalierbares, fehlertolerantes, selbst heilendes und verteiltes System erstellt._

Wird sicher interessant! Beginn ist 18:00 Uhr.

**Comment by RolandKoenig** [comment]
Jop, cooles Thema. 
Diesmal müsst ichs auch wieder schaffen :-)

**Comment by FlorianRappl** [comment]
War sehr nice. Vielen Dank an Ralph!
