### ISSUE TITLE
Vorträge ab März

### ISSUE THREAD

**Issue by FlorianRappl** [DotNetRegensburg/dotnetregensburg.github.io#8]
Ab März wird meine Aktivität in der .NET Usergroup aus geographischen Gründen stark zurückgehen. Meistens werde ich leider nicht mehr an den Treffen teilnehmen können.

Bis jetzt steht noch kein Sprecher für März (und die Folgemonate?) fest. Die Frage ist, ob sich jemand damit auseinander setzen möchte, oder ob nochmal ein paar interessante Sprecher anschreiben sollte. Bevorzugt sollte der Kontakt zum Sprecher auch präsent sein, weshalb letzteres in meinen Augen nur eine Notlösung darstellen sollte.

**Comment by feO2x** [comment]
Ich denke, dass Thomas und ich das zusammen machen können - er hat die notwendigen Kontakte, ich habe die notwendige Zeit, die Leute anzuschreiben.

**Comment by FlorianRappl** [comment]
Hört sich perfekt an. Vielen Dank! Die Homepage aktualisiere ich auf jeden Fall gerne weiterhin; und wenn sich die Gelegenheit bietet nehme ich auch gerne an den Vorträgen teil.

**Comment by FlorianRappl** [comment]
Wie sieht der aktuelle Plan ab Mai aus? Gibt es für Juni / Juli / ... schon Sprecher?

**Comment by FlorianRappl** [comment]
@feO2x irgendwas neues?

**Comment by feO2x** [comment]
Ich werde meinen Vortrag für Mai heute Abend online stellen, die Beschreibung von Timurs Vortrag für Juni muss mir Thomas noch liefern.
Für Juli habe ich bei Thomas Schissler angefragt bzgl. Strategien für automatisierte Tests.

**Comment by FlorianRappl** [comment]
Hört sich gut an! Habe einen Sprecher für ab Juli. Details würden noch geklärt werden aber nun warte ich erstmal auf die nähere Timeline.

**Comment by FlorianRappl** [comment]
@feO2x danke für den Abstract! Wenn Thomas Schissler noch nicht für Juli zusagt hat würde ich den Juli Spot gerne haben - ich habe dort einen sehr kompetenten Sprecher mit einem interessanten Thema.

**Comment by feO2x** [comment]
Bis jetzt hat er sich noch nicht gemeldet. Ich denke, dass wir auch zuerst deinen Vortrag nehmen können.

**Comment by feO2x** [comment]
Thomas Schissler hat gerade geantwortet, er könnte uns folgende Themen anbieten:

Testen greift zu kurz: Qualitätssicherungsstrategien für DevOps
 Qualität entsteht nicht durch Testen allein
 Qualitätssicherung braucht eine Gesamtstrategie
 Neue Möglichkeiten nutzen, neue Wege denken
 Das richtige Testen
Hohe Aufwände für die Qualitätssicherung sind ein oft genanntes Argument gegen häufige Releases. Und nur die heute oftmals manuell ausgeführten Tests zu automatisieren wird nicht erfolgreich sein. Dadurch wird deutlich, dass wir für eine DevOps-Transformation neue Strategien für die Qualitätssicherung brauchen. In diesem Zuge bietet sich dann die Gelegenheit, alte Zöpfe abzuschneiden und das Thema Qualität neu zu definieren. Durch die richtige Strategie lässt sich mit weniger Aufwand mehr Qualität erzielen. Diese Session zeigt verschiedene Möglichkeiten auf und bietet ihnen Inspirationen um Qualitätssicherung in ihrer Organisation neu zu definieren.

Alternativ könnte ich auch noch einen Vortrag zum Thema DevOps anbieten:

DevOps – Agilität auf den Unternehmens-Kontext ausweiten
 Reagieren auf schnellen Wandel im Zuge der Digitalisierung
 Agilität im Unternehmens-Kontext
 Herausforderungen und Chancen
Im Zuge der Digitalisierung nimmt die Geschwindigkeit von Änderungen im Software-Umfeld rasant zu und nimmt zum Teil auch disruptive Züge an. Agilität bietet eine Möglichkeit, schnell und flexibel auf solche Veränderungen reagieren zu können, jedoch genügt hier eine Fokussierung auf Entwicklungs-Teams nicht: DevOps ist nichts weniger als die Ausdehnung von Agilität auf das gesamte Unternehmen. In dieser Session wollen wir beleuchten, welche Chancen aber auch welche Herausforderungen DevOps bietet und ihnen eine Roadmap für eine DevOps-Transformation aufzeigen.

Mich persönlich würde eher Thema 1 interessieren, aber das können wir ja noch abstimmen.

@FlorianRappl Wollen wir ihn für Juli nehmen oder soll ich nochmal verhandeln, ob er auch im September kommen könnte?

**Comment by FlorianRappl** [comment]
@feO2x Wird August ausgelassen? Aber ja, wäre gut wenn wir das versuchen in den September zu legen.

**Comment by feO2x** [comment]
Ja, August wird üblicherweise ausgelassen weil Urlaubszeit - ich mache das mit ihm aus. Hast du Wünsche zum Thema?

**Comment by FlorianRappl** [comment]
Ich wäre für den 2. Vortrag "DevOps – Agilität auf den Unternehmens-Kontext ausweiten". Denke das Thema könnte mehr interessieren (da allgemeiner).

**Comment by feO2x** [comment]
Thomas Schissler kommt am 19. September 2016 mit dem Thema DevOps.

@FlorianRappl Ist er für seinen letzten Vortrag vergütet worden?

**Comment by FlorianRappl** [comment]
Nein (und war auch nie so abgesprochen / geplant). Bzgl. Fahrtkosten müsste er das über die INETA regeln.

**Comment by feO2x** [comment]
Florian, können wir den Talk vom Juli in den Juli vorziehen? Timur Zanagar, der ursprünglich für Juni mit dem Thema "Überblick über Xamarin" vorgesehen war, antwortet mir leider nicht auf meine Anfragen.

**Comment by FlorianRappl** [comment]
(Ich vermute du meinst _Juli in den Juni_)

Ich glaube das wäre fast zu kurzfristig. Muss ich nachfassen.

**Comment by feO2x** [comment]
Also das mit der .NET UG im Juni wird wohl nichts mehr - @FlorianRappl, könntest du bitte einen Termin für Juli ausmachen und das Abstract besorgen?

**Comment by FlorianRappl** [comment]
Mach ich!

Wg. den Termin ist die Tendenz zwischen dem 25. Juli und 1. August. Ich denke der 1. August wäre auch noch ok?

@feO2x: Könnten wir noch kurzfristig einen Talk nächste Woche Montag einbringen? z.B. Gregor Biswanger, @RolandKoenig oder @fancyDevelopment ?

**Comment by feO2x** [comment]
Ob 25. Juli oder 1. August ist egal. Bin mir nicht sicher, ob jemand kurzfristig einen Talk zu Verfügung hat. Bei Gregor habe ich eigentlich schon für Oktober angefragt.

**Comment by FlorianRappl** [comment]
Alles klar. @RolandKoenig und @fancyDevelopment - jemand von euch spontan Lust (bzw. hättet ihr generell ein interessantes Thema?).

**Comment by RolandKoenig** [comment]
Hallo zusammen,
hätte eigentlich schon vorgehabt, dieses Jahr noch oder Anfang nächstes Jahr einen Xamarin-Vortrag mit reinzubringen. Juni ist mir dafür aber leider etwas knapp.
