### ISSUE TITLE
Montag, 14.03.2016: Containers, Windows Fabric and Azure

### ISSUE THREAD

**Issue by FlorianRappl** [DotNetRegensburg/dotnetregensburg.github.io#9]
Wollte auch hier auf den nächsten Vortrag hinweisen.

**Containers, Windows Fabric and Azure - Globally scalable, available architectures in Cloud Environments**

_Container und Micro Services schicken sich an das, "Next Big Thing" in Software Development und Architektur zu werden. Die Technologien haben bereits einen großen Einfluss darauf, wie Applikationen entwickelt und designed werden. Insbesondere moderene Cloud basierte Services setzen auf Container und Micro Services. In diesem Talk werden wir den Container Support von Windows Server 2016 näher beleuchten und aufzeigen, wie die Verwendung von Azure Service Fabric, welche sowohl lokal als auch in der Cloud verfügbar ist, die Entwicklung von hochskallierenden und ausfallsicheren Diensten revolutioniert._

Wird sicher wieder interessant! Beginn ist 18:00 Uhr.

Bitte in den Doodle eintragen: http://doodle.com/poll/w4dx5tqtfy8hyn8w

**Comment by feO2x** [comment]
Wissen wir schon, ob wir im alten oder neuen IT-Speicher sind?

**Comment by FlorianRappl** [comment]
Habe die Adresse auf den neuen Speicher (TechBase) gesetzt, aber nachdem noch kein Raum feststeht bezweifle ich, dass der Ort schon fix ist.

**Comment by feO2x** [comment]
Richtig, Thomas hat mir gerade per Mail geantwortet, dass sich das noch in Klärung befindet.

**Comment by FlorianRappl** [comment]
Alles klar!
